# Generated by Django 3.0.8 on 2020-07-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Grupos de Educação')),
            ],
            options={
                'verbose_name': 'grupo de educação',
                'verbose_name_plural': 'grupos de educação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'matéria',
                'verbose_name_plural': 'matérias',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Assunto da Matéria')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='posts.EducationSubject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'assunto da matéria',
                'verbose_name_plural': 'assuntos das matérias',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='Ano / Período')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='posts.EducationGroup', verbose_name='Grupo de Educação')),
            ],
            options={
                'verbose_name': 'ano ou período',
                'verbose_name_plural': 'anos ou períodos',
                'ordering': ['year'],
            },
        ),
    ]
