# Generated by Django 3.0.8 on 2020-07-24 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador')),
                ('draft', models.BooleanField(default=True, verbose_name='Rascunho?')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Visualizações')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.EducationGroup', verbose_name='Grupo de Educação')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.EducationSubject', verbose_name='Matéria')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.SubjectTopic', verbose_name='Assunto da Matéria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.EducationYear', verbose_name='Ano / Período')),
            ],
            options={
                'verbose_name': 'resumo',
                'verbose_name_plural': 'resumo',
                'ordering': ['-updated_at'],
            },
        ),
    ]
