# Generated by Django 4.0.3 on 2022-04-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200726_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='posts.educationsubject', verbose_name='Matéria'),
        ),
    ]
