# Generated by Django 3.0.8 on 2020-07-24 16:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-_]+$'), 'O nome de usuário só pode conter letras, dígitos ou @/./+/-/_', 'invalid')], verbose_name='Username'),
        ),
    ]
